### ISSUE TITLE
Prettier not formatting

### ISSUE THREAD

**Issue by Morriz** [zhoudonhua/react-native-expo-ts-mobx#1]
Hi, tnx first of all for a fresh starter...but I noticed prettier not working out of the box. Could it be my default vscode' User settings?

**Comment by zhdonghua** [comment]
Hi, @Morriz. I'm sorry to trouble you!  You should install [prettier-vscode](https://github.com/prettier/prettier-vscode)  into vscode.
```
1. CMD + Shift + P -> Format Document
OR
1. Select the text you want to Prettify
2. CMD + Shift + P -> Format Selection
Or
1. Option + Shift + F
```
See more information, https://prettier.io.

**Comment by Morriz** [comment]
sry to come back so late, but I had and have that plugin installed...the txs files somehow don't get picked up. I suspect you forgot to commit something, or have not explained how to wire it.

**Comment by Morriz** [comment]
```
    "tslint": "^5.12.0",
    "tslint-config-prettier": "^1.17.0",
```

**Comment by zhoudonhua** [comment]
> sry to come back so late, but I had and have that plugin installed...the tsx files somehow don't get picked up. I suspect you forgot to commit something, or have not explained how to wire it.

Thx, @Morriz. It's my mistake. I have not add `pre-commit hook`, and you can add it base on [Using TSlint with Prettier](https://alexjover.com/blog/use-prettier-with-tslint-and-be-happy/).

**Comment by Morriz** [comment]
And the packages I listed are not in your package.json
